# BSD 3-Clause License
# Copyright (c) 2022, GM Consult Pty Ltd
# All rights reserved.

name: gmconsult_dev
description: DART utilities for GM Consult developers to lubricate / standardize unit testing.
version: 0.0.7+2
repository: https://github.com/GM-Consult-Pty-Ltd/gmconsult_dev
homepage: https://github.com/GM-Consult-Pty-Ltd
issue_tracker: https://github.com/GM-Consult-Pty-Ltd/gmconsult_dev/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  # -----PubDev Packages (in alphabetic order) -----
  collection: ^1.16.0
  hive: ^2.2.3
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
